// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import FormController from "./form_controller"
application.register("form", FormController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import ValueController from "./value_controller"
application.register("value", ValueController)

import ContentLoaderController from "./content_loader_controller"
application.register("content-loader", ContentLoaderController)